MODEL_NAME: "%MODEL.NAME%"
IC_NAME: "%MODEL.ICS%"
STD_VERSION: "v010"
INI_DATA_PATH: "%DIRS.INI_DATA_PATH%/%CHUNK_START_DATE%"
START_TIME: '%CHUNK_START_YEAR%-%CHUNK_START_MONTH%-%CHUNK_START_DAY%'
END_TIME: '%CHUNK_END_YEAR%-%CHUNK_END_MONTH%-%CHUNK_END_DAY%'
DATA_INNER_STEPS: 24  
INNER_STEPS: 6        
MEMBERS: "%EXPERIMENT.MEMBERS%"
RNG_KEY: "%MEMBER%"
OUTPUT_PATH: "%HPCROOTDIR%/outputs"
TEMP_DIR: "%HPCROOTDIR%/temp/%MODEL.NAME%/%SDATE%/%MEMBER%/"
ICS_TEMP_DIR: "%HPCROOTDIR%/ics_temp/%MODEL.NAME%/%SDATE%/ics/"
HPCROOTDIR: "%HPCROOTDIR%"
MODEL_CHECKPOINT: "%PATHS.SUPPORT_FOLDER%/models/%MODEL.NAME%/%MODEL.CHECKPOINT_NAME%"
STATIC_DATA: "%PATHS.SUPPORT_FOLDER%/static/AIUQ-static.nc"
CLIMATOLOGY_DATA: "%PATHS.SUPPORT_FOLDER%/climatology/AIUQ-climatology.nc"
EERIE_PATH: "%PATHS.SUPPORT_FOLDER%/eerie/"
OUTPUT_TEMP_PATH: "%HPCROOTDIR%/outputs_temp/%MODEL.NAME%/%SDATE%/%MEMBER%/"

OUT_VARS: "%EXPERIMENT.OUT_VARS%"
OUT_FREQ: "%EXPERIMENT.OUT_FREQ%"
OUT_RES: "%EXPERIMENT.OUT_RES%"
OUT_LEVS: "%EXPERIMENT.OUT_LEVS%"